<a href="https://colab.research.google.com/github/cagBRT/Intro-to-Numpy/blob/master/C1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Clone the entire repo.
!git clone -l -s https://github.com/cagBRT/Intro-to-Numpy.git cloned-repo
%cd cloned-repo
!ls

In [0]:
from IPython.display import Image
def page(num):
    return Image("c8-content/c8PythonProgramming"+str(num)+ ".png" , width=640)

# **Numpy Arrays**
Recall Python does not have arrays. <br>
Yet, arrays are really convenient and powerful. <br>
To use arrays in Python, import Numpy.<br>

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. <br><br>
The elements of a NumPy array, or simply an array, are usually numbers, but can also be boolians, strings, or other objects. *When the elements are numbers, they must all be of the same type. For example, they might be all integers or all floating point numbers.*<br><br>
The NumPy arrays takes significantly less amount of memory as compared to python lists.

# **Import Numpy**

In [0]:
import numpy as np

# **Create an Array**

In [0]:
#Create an array of 2 row and 3 columns
a = np.array([[1, 2, 3],[2,4,6]])   
print(type(a))           
print(a.shape)            


**Print an array**

In [0]:
print(a)  

**Change a value in an array**<br>
There are two ways to access a value in a Numpy array<br>
>array_name[row number, column number]<br>
>array_name[row number][colu,mn number]

In [0]:
#Change the value at location (0,0)
a[0,0] = 5                  
print(a)     
print("")
#Change the value at location (1,1)
a[1][1] = 44
print(a)

# **Assignment #1**
1. Create a 4x4 Numpy array<br>
2. Print the values at (0,0)(1,1)(2,2)(3,3)


In [0]:
#Assignment #1


# **Create Filled Arrays**
Numpy allows you to create arrays filled with zeros, ones, a specific number, an identity matrix, and an array filled with random numbers.

**An array of all zeros**<br>
np.zeros((number of rows, number of columns))

In [0]:
a = np.zeros((7,9))   
print(a)              

**An array of all ones**<br>
np.ones((number of rows, number of columns))

In [0]:
b = np.ones((5,4))    
print(b)              


Arrays of: <br>
>A specific number<br>
>>np.full((no. of rows, no of col), number for filling)<br>
<br>

>An identity matrix<br>
>>np.eye(matrix dimension)<br>
<br>

>An index filled with random numbers
>>np.random.random((no. of rows, no of col))


# **Assignment #2**
Create and print the following arrays<br>
1. A 12x10 array filled with the number 45.333<br>
2. A 25x25 identity matrix<br>
3. A 12x30 array filled with random numbers

# **Slice an Array**
Numpy arrays can be sliced into smaller arrays of different sizes. 

In [0]:
#Slicing an array

#Create an array of the following size and values
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)


**Slice the array**<br>
Slice an array using: 
new_array = original_array[first row:last row, first col, last col]

In [0]:
#Create a new array from the center four values
#[[6   7]
# [10 11]]

b = a[1:3, 1:3]
print(b)

**Sliced arrays are changed when the new array or the original array are changed**

In [0]:
print(a)
print("")

#Change a value in the new array
b[0,0] = -22

#Notice -- the value in b was changed. 
#And the value in a was also changed
print(a)

In [0]:
print(b)
print("")

#Change a value in the new array
a[1,1] = -8888

#Notice -- the value in a was changed. 
#And the value in b was also changed
print(b)

# **Assignment #3**
1. Create the following array: 
>[2,6,9,12]<br>
>[5,1,1,8]<br>
>[7,7,5,9]<br>
>[8,9,5,2]<br>

2.Slice the array into two (non-overlapping) 4x2 arrays<br>
3.Change 5 values in the original array. <br>
4.Print the two new arrays, check that the values have changed. <br>


In [0]:
#Assignment #3

a = np.array([[2,6,9,12], [5,1,1,8], [7,7,5,9], [8,9,5,2]])
print(a)

# **Reshaping Arrays**

Numpy has a built in function that allows the user to reshape arrays. <br>
>array-name.reshape(number of rows, number of col)<br>
<br>
The new shape has to have the same number of elements as the old shape. 
<br>
For example:<br>
If the array has a shape of 3x4 (12 elements) it can be reshaped to:<br>
>12x1<br>
>1x12<br>
>2x6<br>
>6x2<br>
>4x3<br>

In [0]:
#Reshape an array
#Step 1: create an array
#Use arange to create an array of evenly
#spaced integers from 0 - 23
a = np.arange(24)
print(a)
#The shape of this array is a vector
print(a.shape)
#Step 2: change the shape of array a
a.reshape(8,3)

# **Assignment #4**
1. Create an array that has 32 elements. 
2. Reshape it into: 
> an array 8x4<br>
>an array 2x16<br>


In [0]:
#Assignment #4

**Reshape an array into three or more dimensions**
Numpy arrays can also be reshaped into multiple dimensions. 
Use the form:<br>
>array-name.reshape(dimension 1, no. of rows, no. of cols)<br>

The criteria about the number of elements must still be obeyed. 


# **Assignment #5**
1. Create an array of 72 elements
2. Reshape the array into 12x3x2 

In [0]:
#Assignment #5


# **Creating an Array from Data in a File**
Numpy allows the user to create arrays from the contents of a file. 


Step 1: Check the access and pathname for the file to be read

In [0]:
!cat /content/cloned-repo/chordProgressions.csv


# **Import genfromtxt**
Use genfromtxt to generate the array from the text file. 
<br>
When reading in data from files, you need to specify the data type. Usually Numpy arrays are used for numbers. <br>
<br>
For the chord-progressions.csv file, there is integer data and string data. <br>
To read it into a Numpy array, you must specify the datatype for each column. <br>
i1 = integer<br>
S20 = string<br>
skip_header will ignore the header row <br> 

In [0]:
from numpy import genfromtxt
chords = genfromtxt("/content/cloned-repo/chordProgressions.csv",  
                    delimiter=',',skip_header=1, dtype=[('1st chord','i1'),('2nd chord','i1') , ('3rd chord','i1'),
                                          ('4th chord','i1'), ('Progression Quality', 'S20')])

In [0]:
print(chords)

In [0]:
print(chords.shape)
cReshape = chords.reshape(28,1)
print(cReshape)

# **Assignment #6**
1. Read the file /content/cloned-repo/data_files/airtravel.csv
2. Ignore the header row
3. Create a Numpy array with the data
4. Convert the months to numbers (JAN = 1,FEB=2, ...Dec=12)


[numpy.genfromtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html)


In [0]:
!cat /content/cloned-repo/airtravel.csv

In [0]:
air_travel=np.genfromtxt("/content/cloned-repo/data_files/airtravel.csv", skip_header=1, delimiter=',', usecols=(1,2,3))

In [0]:
print(air_travel)

# **Airthmetic Operations**
Numpy can perform arithmetic operations on arrays very easily. 
The form for artihmetic operations is: <br>
>np.operation(array1, array2)<br>

The available operations are: <br>
>add<br>
>subtract<br>
>multiply<br>
>divide<br>


In [0]:
#Arithmetic Operations
array1 = np.arange(9).reshape(3,3)
print("Array1 = \n", array1)

array2 = np.arange(4,13).reshape(3,3)
print("Array2 = \n", array2)

In [0]:
sum = np.add(array1, array2)
print(sum)

# **Assignment 7**
1. Create two 5x5 arrays
2. Multiply them, 
3. Subract one from the other
4. Divide one into the other. 


In [0]:
#Assignment #7

# **Sorting Arrays**

Numpy has a built-in sort function. <br>
It has the form: 
>np.sort(array name)


In [0]:
#Sorting arrays
array1 = ([[6,3,1,2], [9,11,6,5], [6,4,7,0]])
print(array1)

In [0]:
#Sort the columns
array_sorted = np.sort(array1, axis=0)
print(array_sorted)

In [0]:
#Sort the rows
array_sorted = np.sort(array1, axis=1)
print(array_sorted)

# **Assignment #8**
1. Create an array with the following values: <br>
>[4,8,1,0,99]
>[1,22,0,76,43]
>[7,7,90,54,3]

2. Sort it along the x axis
3. Sort it along the y axis


In [0]:
#Assignment 8


**Text in Numy Arrays**
Numpy arrays can also sort text 


In [0]:
array1 = ([['w','c'], ['z','f']])
print(array1)
print(np.sort(array1,axis=1))

# **Assignment #9**
1. Create an array with the following values: 
>['dog','fish','cat']<br>
['zebra', 'mouse', 'ox']<br>

2. Sort on the x-axis 
3. Sort on the y-axis


**Sort an array based on a parameter**<br>
A Numpy array can be created with parameter names and types identified. <br>
Then the array can be sorted based on the parameter name. <br>
<br>
Step 1: Create an array with parameter names and types 
Step 2: Sort the array with the form:<br>
>np.sort(array name, order = 'parameter name')


In [0]:
#Sorting arrays by parameter name
#Step 1: create the array with parameter names and types
dt = np.dtype([('name', 'S10'), ('zipcode', int)])
array1 = np.array([('Joe', 95120), ('Mark', 95122), ('Sue', 90210)], dtype=dt)
print(array1)

In [0]:
#Step 2: Sort the array by zipcode
print(np.sort(array1, order='zipcode'))
print(np.sort(array1, order='name'))

# **Assignment #10**
1. Create an array of 10 students with the following information
>Student name, student ID, student major, student GPA<br>
For example: <br>
> >'Bill', 453221, 'CompSci', 2.3

2. Sort the array by each of the features (name, ID, major, GPA)


# **Numpy and MatPlotLib**

You can use Matplotlib with Numpy arrays. <br>
Practice using Matplotlib with Numpy. 

In [0]:
import matplotlib.pyplot as plt

# evenly sampled time at 200ms intervals
t = np.arange(0., 5., 0.2)

# red dashes, blue squares and green triangles
plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^')
plt.show()

# **Assignment #11**
1. Create an array with the following values: <br>
>[22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]
2. Plot the array using a blue line
3. Plot the square of the array using red squares
4. Plot the cube of the array using green dashes

**Matplotlib can be used to make scatterplots**<br>
Use this link to research [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html)

In [0]:
#Create arrays and add them to a scatter plot
#Random number generators are used in this example
data = {'a': np.arange(50),
        'c': np.random.randint(0, 50, 50),
        'd': np.random.randn(50)}
data['b'] = data['a'] + 10 * np.random.randn(50)
data['d'] = np.abs(data['d']) * 100

plt.scatter('a', 'b', c='c', s='d', data=data)
plt.xlabel('entry a')
plt.ylabel('entry b')
plt.show()

# **Assignment #12**
1. Create four Numpy arrays 
2. Add them to a scatterplot

# **Additional Examples using Matplotlib**
**Optional**<br>
This section is optional. 
Enjoy creating different plots and experimenting with Matplotlib

In [0]:
def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure()
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')
plt.show()

In [0]:
#https://matplotlib.org/gallery/lines_bars_and_markers/bar_stacked.html#sphx-glr-gallery-lines-bars-and-markers-bar-stacked-pynumpytut
import numpy as np
import matplotlib.pyplot as plt


N = 5
menMeans = (20, 35, 30, 35, 27)
womenMeans = (25, 32, 34, 20, 25)
menStd = (2, 3, 4, 1, 2)
womenStd = (3, 5, 2, 3, 3)
ind = np.arange(N)    # the x locations for the groups
width = 0.35       # the width of the bars: can also be len(x) sequence

p1 = plt.bar(ind, menMeans, width, yerr=menStd)
p2 = plt.bar(ind, womenMeans, width,
             bottom=menMeans, yerr=womenStd)

plt.ylabel('Scores')
plt.title('Scores by group and gender')
plt.xticks(ind, ('G1', 'G2', 'G3', 'G4', 'G5'))
plt.yticks(np.arange(0, 81, 10))
plt.legend((p1[0], p2[0]), ('Men', 'Women'))

plt.show()

In [0]:
#https://matplotlib.org/gallery/pie_and_polar_charts/polar_bar.html#sphx-glr-gallery-pie-and-polar-charts-polar-bar-py

import numpy as np
import matplotlib.pyplot as plt


# Fixing random state for reproducibility
np.random.seed(19680801)

# Compute pie slices
N = 20
theta = np.linspace(0.0, 2 * np.pi, N, endpoint=False)
radii = 10 * np.random.rand(N)
width = np.pi / 4 * np.random.rand(N)
colors = plt.cm.viridis(radii / 10.)

ax = plt.subplot(111, projection='polar')
ax.bar(theta, radii, width=width, bottom=0.0, color=colors, alpha=0.5)

plt.show()