https://numpy.org/devdocs/reference/routines.array-manipulation.html


In [ ]:
# Clona el repositorio completo
!git clone -l -s https://github.com/cagBRT/Intro-to-Numpy.git cloned-repo
%cd cloned-repo
!ls

In [ ]:
from IPython.display import Image
def page(num):
    return Image("c8-content/c8PythonProgramming"+str(num)+ ".png" , width=640)

# **Arreglos (array) de Numpy**

Debemos recordar que Python no tiene arreglos. Aun así, los arreglos son sumament convenientes y poderosos.

Para usar arreglos en Python, podemos importar Numpy

Numpy es la librería base para la computación científica en Python. Nos provee con un arreglo multidimensional de alto rendimiento, así como herramientas para trabajar con estos arreglos.
<br><br>
Los elementos de un arreglo de NumPy, o simplemente arreglo, son normalmente numéricos, pero pueden ser también boleanos, strings u otro tipo de objetos. *Cuando los elementos son números todo deben de ser del mismo tipo. Por ejemplo, deben de ser todos enteros o números de punto flotante (float)*
<br><br>
Los arreglos de NumPy ocupan una cantidad de memoria significativamente menor comparada con las listas de python.

# **Importa Numpy**

In [ ]:
import numpy as np

# **Crea un Arreglo**

In [ ]:
#Crea un arreglo de 2 renglones y 3 columnas
a = np.array([[1, 2, 3],[2,4,6]])   
print(type(a))           
print(a.shape)            

**Imprime el arreglo**

In [ ]:
print(a)  

**Modifica un valor en el arreglo**<br>

Existen dos maneras para acceder a un valor en un arreglo Numpy<br>

>nombre_de_arreglo[numero de renglon, numero de columna]
>nombre_de_arreglo[numero de renglon][numero de columna]

In [ ]:

#Cambia el valor en la locacion (0,0)
a[0][0] = 5                  
print(a)     
print("")
#Cambia el valor en la locacion (1,1)
a[1][1] = 44
print(a)

# **Actividad #1**

1. Crea un arreglo de numpy 4x4
2. Imprime los valores en (0,0)(1,1)(2,2)(3,3)


In [ ]:
#Actividad #1


# **Crea arreglos llenos**

Numpy permite la creación de arreglos rellenos con ceros, unos, un numero especifico, una matriz identidad, o un array lleno de números aleatorios

**Un arreglo con solo ceros**<br>
np.zeros((number of rows, number of columns))

In [ ]:
a = np.zeros((7,9))   
print(a)              

**Un arreglo con solo unos**<br>
np.ones((number of rows, number of columns))

In [ ]:
b = np.ones((5,4))    
print(b)              


Arreglos de: <br>
>Un número específico<br>
>>np.full((no. of rows, no of col), number for filling)<br>
<br>

>Una matriz identidad<br>
>>np.eye(matrix dimension)<br>
<br>

>Números aleatorios
>>np.random.random((no. of rows, no of col))


# **Actividad #2**
Crea e imprime los siguientes arrays<br>
1. Un arreglo 12x10 relleno con el número 45.333
2. Una matriz identidad 25x25 
3. Un arreglo 12x30 relleno con números aleatorios.

# **Partir un arreglo**
Los arreglos de numpy pueden ser partidos en arreglos más pequeños de diferentes tamaños

In [ ]:
#Partiendo un arreglo

#Crea un arreglo con el siguiente tamaño y valores
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]
#  [13 14 15 16]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(a)


**Parte el arreglo**<br>
Parte el arreglo de la siguiente manera 
nuevo_arreglo = arreglo_original[primer renglon:ultimo renglon, primera columna: ultima columna]

In [ ]:
#Crea un nuevo arreglo con los valores del centro de la matriz
#[[6   7]
# [10 11]]

b = a[1:3, 1:3]
print(b)

**Los arreglos partidos se modifican cuando el nuevo arreglo o el arreglo original son modificados**

In [ ]:
print(a)
print("")

#Cambia un valor en el nuevo arreglo
b[0,0] = -22

#Mira como que el valor de b ha sido cambiado 
#Y el valor en a tambien
print(a)

In [ ]:
print(b)
print("")

#Cambia un valor en el arreglo original
a[1,1] = -8888

#Mira como que el valor de a ha sido cambiado 
#Y el valor en b tambien
print(b)

# **Actividad #3**
1. Crea el siguiente arreglo 
>[2,6,9,12]<br>
>[5,1,1,8]<br>
>[7,7,5,9]<br>
>[8,9,5,2]<br>


2. Parte el arreglo en dos arreglos (no superpuestos) de 4x2
3. Cambia 5 valores en el arreglo original
4. Imprime los 2 nuevos arreglos, revisa que los valores hayan cambiado.

In [ ]:
#Actividad #3

a = np.array([[2,6,9,12], [5,1,1,8], [7,7,5,9], [8,9,5,2]])
print(a)

In [ ]:
#@title
#Code by Michael Harrington
a = np.array([[2,6,9,12], [5,1,1,8], [7,7,5,9], [8,9,5,2]])
print(a)
a1, a2 = np.hsplit(a, 2)
a[0,0] = 10
a[2,2] = 14
a[1,1] = 17
a[3,3] = 19
a[1,2] = 23
print (a1)
print (a2)

# **Redimensionando(Reshaping) Arreglos**
 
Numpy tiene una función integrada que permite al usario redimensionar los arreglos<br>
>nombre_de_arreglo.reshape(numero de renglones, numero de columnas)
<br>
La nueva forma debe de tener el mismo numero de elementos que forma anterior.
<br>
Por ejemplo:<br>

Si el arreglo tiene una forma de 3x4 (12 elementos) puede redimensionarse a:
>12x1<br>
>1x12<br>
>2x6<br>
>6x2<br>
>4x3<br>

In [ ]:
#Redimensiona a un arreglo
#Paso 1: crea un arreglo
#Una arange para crear un arreglo de enteros 
# igualmente espaceados de 0 - 23
a = np.arange(24)
print(a)
#La forma de este arreglo es un vector
print(a.shape)
#Paso 2: cambia para forma del arreglo a
a.reshape(8,3)

# **Actividad #4**
1. Crea un arreglo que tenga 32 elementos 
2. Redimensiona a: 
>un arreglo de 8x4<br>
>un arreglo de 2x16<br>


In [ ]:
#Actividad #4

**Redimensiona un arreglo en 3 o más dimensiones:**

Los arreglos también pueden ser redimensionados a múltiples dimensiones. 
Usa la forma:
>nombre_de_arreglo.reshape(dimension 1, no. de renglones, no. de columnas)<br>

El criterio respecto al número de elementos aun debe de ser obedecida


# **Actividad #5**
1. Crea un arreglo de 72 elementos
2. Redimensiona el arreglo en 12x3x2 

In [ ]:
#Actividad #5


# **Crea un arreglo con datos en un archivo**
Numpy permite al usario crear arreglos a partir de los contenidos de un archivo.

Paso 1: Revisa el acceso a la ruta del archivo a ser leído

In [ ]:
!cat /content/cloned-repo/chordProgressions.csv


# **Importa genfromtxt**
Usa genfromtxt para generar un arreglo de un archivo de texto.
<br>

Cuando lees datos de un documentos, necesitas específicar el tipo de datos. Usualmente los arreglos de Numpy son usados para números<br>
<br>

En el archivo chord-progressions.csv, existen datos enteros y strings. Para convertir el archivo en un arreglo numpy, debes específicar el tipo de dato para cada columna
<br>
i1 = entero<br>
S20 = string<br>
skip_header ignorará el renglón de encabezados<br> 

In [ ]:
from numpy import genfromtxt
chords = genfromtxt("/content/cloned-repo/chordProgressions.csv",  
                    delimiter=',',skip_header=1, dtype=[('1st chord','i1'),('2nd chord','i1') , ('3rd chord','i1'),
                                          ('4th chord','i1'), ('Progression Quality', 'U20')])

In [ ]:
print(chords)

In [ ]:
print(chords.shape)
cReshape = chords.reshape(28,1)
print(cReshape)

# **Actividad #6**
1. Lee el archivo /content/cloned-repo/airtravel.csv
2. Ignora el renglón de encabezados
3. Crea un arreglo con los datos
4. Convierte los meses en números (JAN = 1,FEB=2, ...Dec=12)

Pista:<br><br>
Asegurate de entender qe valor está almacenado en el arreglo<br>
print("airtravel[0][0] = ",airtravel[0][0])


[numpy.genfromtxt](https://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html)


# **Operaciones aritméticas**
Numpy puede realizar operaciones aritméticas con arreglos de forma sencilla.
La forma para las operaciones arimrtméticas son:
>np.operation(arreglo1, arreglo2)<br>

Las operaciones disponibles son: <br>
>suma (add)<br>
>recta (substract)<br>
>multiplicación (multiply)<br>
>división (divide)<br>


In [ ]:
#Operaciones aritméticas
array1 = np.arange(9).reshape(3,3)
print("Arreglo 1 = \n", array1)

array2 = np.arange(4,13).reshape(3,3)
print("Arreglo 2 = \n", array2)

In [ ]:
sum = np.add(array1, array2)
print(sum)

# **Actividad 7**
1. Crea dos arreglos de 5x5
2. Multiplicalos, 
3. Resta uno del otro
4. Divide uno entre el otro. 


In [ ]:
#Actividad #7

**Producto punto**<br>
>a · b = ax × bx + ay × by<br>

Para más de dos dimensiones....<br>
>a · b = ax × bx + ay × by + az × bz<br>

In [ ]:
v = np.array([9,10])
w = np.array([11, 12])

# Producto interno de los vectores; ambos dan 219
print(v.dot(w))
print(np.dot(v, w))


Si estás interesado en aprender más respecto a funciones de algebra linear, revisa este enlance: <br>
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


Encuentra el producto punto de:<br>
[22,33,44] [11,22,33]

# **Ordenando arreglos**

Numpy tiene una función de ordenamiento integrada. <br>
Tiene la forma: 
>np.sort(array name)


In [ ]:
#Ordenando arreglos
array1 = np.array([[6,3,1,2], [9,11,6,5], [6,4,7,0]])
print(array1)

In [ ]:
#Ordena las columnas
array_sorted = np.sort(array1, axis=0)
print(array_sorted)

In [ ]:
#Ordena los renglones
array_sorted = np.sort(array1, axis=1)
print(array_sorted)

# **Actividad #8**
1. Crea un arreglo con los siguientes valores: <br>
>[4,8,1,0,99]
>[1,22,0,76,43]
>[7,7,90,54,3]

2. Ordena en torno de eje x
3. Ordena en torno a el eje y


In [ ]:
#Actividad 8

**Texto en arreglos de numpy:**  Numpy también puede ordenar texto. 


In [ ]:
array1 = np.array([['w','c'], ['z','f']])
print(array1)
print(np.sort(array1,axis=1))

# **Actividad #9**
1. Crea un arreglo con los siguientes valores: 
>['dog','fish','cat']<br>
['zebra', 'mouse', 'ox']<br>

2. Ordena en el eje x
3. Ordena en el eje y


**Ordena un arreglo basado en un parámetro**<br>
 Un arreglo de numpy puede ser creado con nombres de parametro y tipos identificados<br>

Entonces el arreglo puede ser ordenado basado en el nombre del parámetro. <br>
<br>
Paso 1: Crea un arreglos con el nombre de los parametros y los tipos.

Paso 2: Ordena el arreglo de la siguiente manera:<br>
>np.sort(nombre del arreglo, order = 'nombre del parámetro')


In [ ]:
#Ordenando arreglos por nombre de parametro
#Paso 1: Crea un arreglos con el nombre de los parametros y los tipos.
dt = np.dtype([('name', 'S10'), ('zipcode', int)])
array1 = np.array([('Joe', 95120), ('Mark', 95122), ('Sue', 90210)], dtype=dt)
print(array1)

#The b in the output is for bytestrings

In [ ]:
#Paso 2: ordena el arreglo por el nombre del parámetro
print(np.sort(array1, order='zipcode'))
print(np.sort(array1, order='name'))

# **Actividad #10**
1. Crea un arreglo de 10 estudiantes con la siguiente información:
>nombre de estudiante, ID de estudiante, carrera, GPA<br>
For example: <br>
> >'Bill', 453221, 'CompSci', 2.3

2. Ordena el arreglo por cada una de las características (name, ID, major, GPA)


# **Numpy y MatPlotLib**


Puedes usar Matplotlib con arreglos de Numpy.

In [ ]:
import matplotlib.pyplot as plt

# tiempo muestreado en intervalos de 200 ms
t = np.arange(0., 5., 0.2)

# rayas rojas, cuadrados azules y triangulos verdes
plt.plot(t, t, 'r--', t, t**2, 'bs', t, t**3, 'g^')
plt.show()

# **Actividad #11**
1. Crea un arrego con los siguientes valores: <br>
>[22,87,5,43,56,73,55,54,11,20,51,5,79,31,27]
2. Grafica el arreglo usando una linea azul
3. Grafica el cuadrado del arreglo usando cuadrados rojos
4. Grafica el cubo del arreglo usando rayas verdes

**Matplotlib puede ser usado para hacer gráficos de dispersión**<br>
Usa el link [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html)

In [ ]:
#Crea arreglos y agregalos al grafico de dispersion
#Para este ejemplo, se usan generadores de numeros aleatorios
data = {'a': np.arange(50),
        'c': np.random.randint(0, 50, 50),
        'd': np.random.randn(50)}
data['b'] = data['a'] + 10 * np.random.randn(50)
data['d'] = np.abs(data['d']) * 100

plt.scatter('a', 'b', c='c', s='d', data=data)
plt.xlabel('entry a')
plt.ylabel('entry b')
plt.show()

# **Assignment #12**
1. Crea cuatro arreglos de Numpy 
2. Agregalos al scatterplot

# **Ejemplos adicionales usando Matplotlib**
**Opcional**<br>
Esta sección es opcional. 

Disfruta creando diferentes gráficos y experimentando con Matplotlib

In [ ]:
def f(t):
    return np.exp(-t) * np.cos(2*np.pi*t)

t1 = np.arange(0.0, 5.0, 0.1)
t2 = np.arange(0.0, 5.0, 0.02)

plt.figure()
plt.subplot(211)
plt.plot(t1, f(t1), 'bo', t2, f(t2), 'k')

plt.subplot(212)
plt.plot(t2, np.cos(2*np.pi*t2), 'r--')
plt.show()

In [ ]:
#https://matplotlib.org/gallery/lines_bars_and_markers/bar_stacked.html#sphx-glr-gallery-lines-bars-and-markers-bar-stacked-pynumpytut

N = 5
menMeans = (20, 35, 30, 35, 27)
womenMeans = (25, 32, 34, 20, 25)
menStd = (2, 3, 4, 1, 2)
womenStd = (3, 5, 2, 3, 3)
ind = np.arange(N)    # las locaciones de x para los grupos
width = 0.35       # la anchura de las barras: también puede ser len(x) 
p1 = plt.bar(ind, menMeans, width, yerr=menStd)
p2 = plt.bar(ind, womenMeans, width,
             bottom=menMeans, yerr=womenStd)

plt.ylabel('Scores')
plt.title('Scores by group and gender')
plt.xticks(ind, ('G1', 'G2', 'G3', 'G4', 'G5'))
plt.yticks(np.arange(0, 81, 10))
plt.legend((p1[0], p2[0]), ('Men', 'Women'))

plt.show()

In [ ]:
#https://matplotlib.org/gallery/pie_and_polar_charts/polar_bar.html#sphx-glr-gallery-pie-and-polar-charts-polar-bar-py

# Ajustando la semilla para permitir la replicabilidad
np.random.seed(19680801)

# Calcula las partes del grafico de pie
N = 20
theta = np.linspace(0.0, 2 * np.pi, N, endpoint=False)
radii = 10 * np.random.rand(N)
width = np.pi / 4 * np.random.rand(N)
colors = plt.cm.viridis(radii / 10.)

ax = plt.subplot(111, projection='polar')
ax.bar(theta, radii, width=width, bottom=0.0, color=colors, alpha=0.5)

plt.show()